### ISSUE TITLE
Error when building with Android Canary14？

### ISSUE THREAD

**Issue by watanavex** [DroidKaigi/conference-app-2021#407]
Is there any problem in your environment?

## Kind (Required)

- Other

 ## Overview (Required)
My environment
macOS Big Sur 11.2.1
KMM Plugin 0.2.3(203-1.4.32-357-IJ)-52

- It seems to be caused by the version of Android Gradle Plugin.

| AS Canary 12<br>AGP 7.0.0-alpha12 | AS Canary 13<br>AGP 7.0.0-alpha13 | AS Canary 13<br>AGP 7.0.0-alpha14  | AS Canary 14<br>AGP 7.0.0-alpha14 |
|--|--|--|--|
| No problem👍 | - Could not find `io.ktor:ktor-client-ios`<br>- Unable to resolve the reference in iOS code. | - Could not find `io.ktor:ktor-client-ios`<br>- Unable to resolve the reference in iOS code.<br>- There is no feature named `GRADLE_METADATA` <br>- oss-licenses-plugin and crashlytics throwing errors during build | - Could not find `io.ktor:ktor-client-ios`<br>- Unable to resolve the reference in iOS code.<br>- There is no feature named `GRADLE_METADATA`<br>- oss-licenses-plugin and crashlytics throwing errors during build |

 ## Links	

-

**Comment by watanavex** [comment]
I'm sorry, but this report may be wrong.

`AS Canary 12&AGP 7.0.0-alpha12` 
This combination also caused a situation where the reference was not found in the iOS code.
I will try to sort out the situation a bit more.

**Comment by watanavex** [comment]
`AS Canary 12&AGP 7.0.0-alpha12`. 
For this combination, there is no problem in 87e75aa. But in e5c8f25, I have a problem with the IOS code😂
- Could not find io.ktor:ktor-client-ios
- Unable to resolve the reference in iOS code.

**Comment by watanavex** [comment]
That's my current guess.

These are problems unrelated to the plugin version
- Could not find io.ktor:ktor-client-ios
- Unable to resolve the reference in iOS code.

These are problems related to the plugin version
- There is no feature named GRADLE_METADATA 
- oss-licenses-plugin and crashlytics throwing errors during build

**Comment by myihsan** [comment]
Here is my thought.

> There is no feature named GRADLE_METADATA

https://docs.gradle.org/7.0-rc-1/release-notes.html
It seems like this flag is removed and it has been inactive since 6.0.
So we may just remove `enableFeaturePreview("GRADLE_METADATA")` from `settings.gradle`?

> Could not find io.ktor:ktor-client-ios

Missing `Dep.Ktor.bom` in `iosMain.dependencies`?

> Unable to resolve the reference in iOS code.

https://github.com/DroidKaigi/conference-app-2021/blob/e5c8f2542f517acdd16ccc0f79e991742d561d2d/data/api/build.gradle#L23-L28

Will be solved after resolving Firebase auth dependencies?

After handling the issues above, the project sync successfully and the references in iosMain are resolved.
However, I can't verify my thought since the issue below block builds😇

> oss-licenses-plugin and crashlytics throwing errors during build

https://github.com/google/play-services-plugins/issues/172

**Comment by watanavex** [comment]
@myihsan  Thank you❗️

> Unable to resolve the reference in iOS code.

This problem has been resolved.
No more support for hierarchical structures.
https://github.com/DroidKaigi/conference-app-2021/pull/402

**Comment by takahirom** [comment]
Thank you for your advice! I'm trying to fix it below.
https://github.com/DroidKaigi/conference-app-2021/pull/408
