### ISSUE TITLE
Add DroidKaigi 2021 Article item in FeedScreen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#622]
## Kind (Required)

- Improvement

 ## Overview (Required)

- We want to make it easy for users to navigate to the DroidKaigi2021 timetable from the FeedScreen.
- Right now I'm showing the first Feed article, but I'd like to show DroidKaigi2021 until November.
![image](https://user-images.githubusercontent.com/1386930/133979653-7cd819fa-f784-4462-be6f-3f02a42b5ba7.png)

 ## Links	

- https://www.figma.com/file/IFlrbfmBSdYvUz7VmSzfLV/DroidKaigi_2021_official_app?node-id=2313%3A772

**Comment by Aqua-ix** [comment]
I wil try this issue🙋

**Comment by takahirom** [comment]
Thanks! Assigned!

**Comment by takahirom** [comment]
@Aqua-ix 
This issue has a milestone date of 10/4. If you have any problems, please let me know! 🙏

**Comment by Aqua-ix** [comment]
Thank you for following me. I'm sorry it took a long time to this issue.
Since this is my first time using Jetpack Compose, it took me a while to understand the code.

There is one thing I am wondering about.
I understand that I need to replace the feedItem, which is the argument of the FirstFeedItem called in the following location, with the data of the timetable, but I'm a little confused about where to write the data of the feedItem to be replaced here. .. Please let me know if there is any good way.

https://github.com/DroidKaigi/conference-app-2021/blob/a33c1fa7b2/uicomponent-compose/feed/src/main/java/io/github/droidkaigi/feeder/feed/FeedScreen.kt#L324-L331

**Comment by takahirom** [comment]
I think it would be a good idea to add a composable function like "DroidKaigi2021ArticleItem".
If it is difficult to implement in FeedList, how about adding a DroidKaigi2021ArticleItem that can be seen in Preview? 💭 

I'm sure we can come up with the FeedList logic later.
I think some refactoring is needed to separate the items in FeedList. 👀

**Comment by Aqua-ix** [comment]
Thank you for your advice.
I was able to display the article on the FeedScreen.

One of the problems at the moment is that it is difficult to implement the process of saving Favorite to DB with the current implementation.
Send a draft pull request once because the rest of the implementation task is just that favorite. I would appreciate it if you could take a look at the code and give me an idea.
